from io import BytesIO

from fpdf import FPDF

from app.schemas.invoice import Invoice, InvoiceStatus

# Status badge colours (R, G, B)
_STATUS_COLOR: dict[InvoiceStatus, tuple[int, int, int]] = {
    InvoiceStatus.paid:      (25,  135,  84),
    InvoiceStatus.sent:      ( 2,  118, 189),
    InvoiceStatus.draft:     (108, 117, 125),
    InvoiceStatus.overdue:   (220,  53,  69),
    InvoiceStatus.cancelled: (173, 181, 189),
}


def build_invoice_pdf(invoice: Invoice) -> bytes:
    """Generate a PDF for a single invoice and return raw bytes."""
    pdf = FPDF(orientation="P", unit="mm", format="A4")
    pdf.set_margins(20, 20, 20)
    pdf.set_auto_page_break(auto=True, margin=20)
    pdf.add_page()

    w = pdf.w - 40  # usable width

    # Title
    pdf.set_font("Helvetica", "B", 26)
    pdf.set_text_color(33, 37, 41)
    pdf.cell(0, 12, "INVOICE", ln=True)
    pdf.ln(2)

    # Invoice meta + status on same row
    col = 55  # label column width

    def meta_row(label: str, value: str) -> None:
        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(108, 117, 125)
        pdf.cell(col, 6, label)
        pdf.set_font("Helvetica", "B", 9)
        pdf.set_text_color(33, 37, 41)
        pdf.cell(0, 6, value, ln=True)

    meta_row("Invoice Number", invoice.invoice_number)
    meta_row("Issued", invoice.issued_date.strftime("%b %d, %Y"))
    meta_row("Due", invoice.due_date.strftime("%b %d, %Y"))
    if invoice.paid_date:
        meta_row("Paid", invoice.paid_date.strftime("%b %d, %Y"))

    # Status pill
    r, g, b = _STATUS_COLOR.get(invoice.status, (108, 117, 125))
    pdf.ln(2)
    pdf.set_font("Helvetica", "B", 8)
    pdf.set_text_color(r, g, b)
    pdf.cell(0, 5, invoice.status.upper(), ln=True)

    if invoice.is_overdue:
        pdf.set_font("Helvetica", "", 8)
        pdf.set_text_color(220, 53, 69)
        pdf.cell(0, 5, f"{invoice.days_overdue} days overdue", ln=True)

    pdf.ln(6)

    # Divider
    pdf.set_draw_color(222, 226, 230)
    pdf.line(20, pdf.get_y(), 20 + w, pdf.get_y())
    pdf.ln(6)

    # Bill To
    pdf.set_font("Helvetica", "B", 8)
    pdf.set_text_color(108, 117, 125)
    pdf.cell(0, 5, "BILL TO", ln=True)
    pdf.ln(1)
    pdf.set_font("Helvetica", "B", 11)
    pdf.set_text_color(33, 37, 41)
    pdf.cell(0, 6, invoice.client_name, ln=True)
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(108, 117, 125)
    pdf.cell(0, 5, str(invoice.client_email), ln=True)
    pdf.ln(10)

    # Line items table
    desc_w = w - 50

    # Header
    pdf.set_fill_color(241, 243, 245)
    pdf.set_font("Helvetica", "B", 8)
    pdf.set_text_color(108, 117, 125)
    pdf.cell(desc_w, 8, "  DESCRIPTION", fill=True)
    pdf.cell(50, 8, "AMOUNT", fill=True, align="R", ln=True)

    # Single line item (the invoice amount)
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(33, 37, 41)
    description = invoice.description or "Professional services"
    pdf.cell(desc_w, 10, f"  {description}")
    pdf.cell(50, 10, f"{invoice.currency} {float(invoice.amount):,.2f}", align="R", ln=True)

    # Totals
    pdf.set_draw_color(222, 226, 230)
    pdf.line(20, pdf.get_y(), 20 + w, pdf.get_y())
    pdf.ln(3)

    def total_row(label: str, value: str, bold: bool = False, color: tuple = (33, 37, 41)) -> None:
        style = "B" if bold else ""
        size = 11 if bold else 9
        pdf.set_font("Helvetica", style, size)
        pdf.set_text_color(108, 117, 125 if not bold else color[0])
        pdf.cell(desc_w, 7, label)
        pdf.set_text_color(*color)
        pdf.cell(50, 7, value, align="R", ln=True)

    collected = float(invoice.collected_amount)
    total = float(invoice.amount)
    balance = total - collected

    total_row("Subtotal", f"{invoice.currency} {total:,.2f}")

    if collected > 0 and invoice.status == InvoiceStatus.paid:
        pdf.set_text_color(25, 135, 84)
        pdf.set_font("Helvetica", "", 9)
        pdf.cell(desc_w, 7, "Amount Paid")
        pdf.cell(50, 7, f"- {invoice.currency} {collected:,.2f}", align="R", ln=True)

    if balance > 0.001 and invoice.status != InvoiceStatus.paid:
        color = (220, 53, 69) if invoice.is_overdue else (33, 37, 41)
        total_row("Balance Due", f"{invoice.currency} {balance:,.2f}", bold=True, color=color)
    else:
        total_row("Total", f"{invoice.currency} {total:,.2f}", bold=True)

    # Footer
    pdf.set_y(-20)
    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(173, 181, 189)
    pdf.cell(0, 5, f"Generated by Invoice Ledger - {invoice.invoice_number}", align="C")

    buf = BytesIO()
    buf.write(bytes(pdf.output()))
    return buf.getvalue()
